# Generated by Django 5.0.6 on 2024-06-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_message_timestamp'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE myapp_privatemessage;'),
    ]
